### ISSUE TITLE
Resolving adposition spelling variants

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#51]
Each adposition has a citation form and may have variants. For example, the citation form for all possessives is `'s`, and possessive pronouns need to be linked to this. "Toward"/"towards" and "out of"/"outta" may be considered conventionalized variant spellings. Moreover, annotated sentences may have adpositions with nonstandard spellings or capitalization. The `p` Markdown macro thus needs to be able to link to an adposition whose canonical name is different from the one used in the sentence.

Proposed solution:

1. Extend the `p` macro to include a display spelling that differs from the canonical lemma: `[p my en/'s]` or `[p my en/'s Possessor]`. `[p en/'s]` would continue to work and be equivalent to `[p 's en/'s]`.

2. To avoid verbosity in the Markdown for standard possessive pronouns and other spelling variants, `[p en/my]` and similar should, in the absence of a matching citation form, search for a match in the `other_forms` field. If exactly one is found, the link will point to that adposition.

**Comment by ablodge** [comment]
Currently, we only log `Usage`s of adpositions that aren't typos or abbreviations. Consider fixing later.

**Comment by ablodge** [comment]
'1' is accomplished by the macro `pspecial` as in `[pspecial en/'s my Possessor]`. I added a new macro to avoid further overloading `p`. 
'2' is a bit harder, but is currently implemented as function `Adposition.normalized_adp()` with hardcoded lists of standard spelling variants. (I have implementation of the same function using `other_forms` in comments.) The trouble is the list of spelling variants has to be hardcoded somewhere before `Adposition`s and `PTokenAnnotation`s can be imported. Otherwise the script won't know where to send each `Adposition` foreign key.

**Comment by nschneid** [comment]
OK, I guess my assumption was that adpositions with `other_forms` would be manually created before importing any tokens. Should we support deleting an adposition after it's been created and merging its tokens with another adposition?

**Comment by ablodge** [comment]
I can do it that way. Is that convenient for Hebrew and other languages where adpositions have more than one variant?

**Comment by nschneid** [comment]
If you're talking about pronominal inflections in Hebrew, those are not reflected in the lemma, so we're OK as long as long as the text has been morphologically processed.

In English we can't rely on lemmas for possessives because the current UD policy is super weird: https://github.com/UniversalDependencies/docs/issues/517
