### ISSUE TITLE
Speed up article display

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#96]
Thinking about this, I notice that on master, most articles aren't listed with subcategories whereas on wiki-data almost everything is a subcategory of something else (compare the articles for English where it lists subcategories). Should we fix this? Is there anything else that might cause the slow display?

**Comment by nschneid** [comment]
It seems unnecessary to have usages as subcategories of adpositions, because we're already displaying the list of usages associated with the adposition.

Are there other kinds of pages where you're seeing subcategories listed?

**Comment by ablodge** [comment]
When I import models through admin I assign a parent. Right now category parents and url parents are treated the same. So an Adposition is a subcategory of a Language, and a Usage is a subcategory of an Adposition.

**Comment by ablodge** [comment]
Should parent categories all be set to none?

**Comment by nschneid** [comment]
Ah. Yeah, maybe set them to none. We already have structured relationships between supersenses, languages, adpositions, construals, usages. We can reserve the use of the category system for custom articles that are associated with various pieces of information. (I don't recall what the manual creation forms for supersenses, etc. do in terms of categories.)

**Comment by ablodge** [comment]
Okay. No more category parents. I'll update the db when I have time.

**Comment by ablodge** [comment]
I used [cProfile](https://docs.python.org/3/library/profile.html#the-python-profilers) to time our code. This is the output for the top slowest functions:

```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1   98.354   98.354   98.354   98.354 {built-in method _winapi.WaitForSingleObject}
     9075    0.720    0.000    0.720    0.000 {built-in method nt.stat}
     1145    0.201    0.000    0.259    0.000 <frozen importlib._bootstrap_external>:830(get_data)
     5470    0.188    0.000    0.188    0.000 {built-in method winreg.OpenKey}
     1145    0.168    0.000    0.168    0.000 {built-in method marshal.loads}
      795    0.118    0.000    0.118    0.000 {built-in method nt.listdir}
3589/3454    0.079    0.000    0.434    0.000 {built-in method builtins.__build_class__}
    18278    0.078    0.000    0.126    0.000 cell.py:75(_get_column_letter)
      550    0.070    0.000    0.070    0.000 {built-in method io.open}
    33/30    0.066    0.002    0.089    0.003 {built-in method _imp.create_dynamic}
     1145    0.058    0.000    0.058    0.000 {method 'read' of '_io.FileIO' objects}
      674    0.050    0.000    0.050    0.000 {built-in method nt._isdir}
     5469    0.042    0.000    0.042    0.000 {built-in method winreg.EnumKey}
 1912/390    0.039    0.000    0.110    0.000 sre_parse.py:470(_parse)
```

**Comment by nschneid** [comment]
What does this mean? I don't have any experience profiling Django code, but there are blog posts with advice for how to do it.

**Comment by ablodge** [comment]
We can use [django-silk](https://github.com/jazzband/django-silk).

**Comment by ablodge** [comment]
Error installing django-silk:

> (urls.W005) URL namespace 'wiki:django-silk' isn't unique. You may not be able to reverse all URLs in this namespace

**Comment by ablodge** [comment]
I fixed the above by adding silk's url in url.py in testproject instead of wiki.plugins.metadata.

**Comment by ablodge** [comment]
Error message:

> wiki 0.3.1 has requirement django-mptt<0.9,>=0.8.6, but you'll have django-mptt 0.9.0 which is incompatible.

**Comment by nschneid** [comment]
FYI, django-wiki 0.3.1 was released Feb 10, which is after we branched from it. This could cause problems (I'm not sure). Actually I'm not sure why we need to do `pip install wiki` given that the Xposition codebase contains the django-wiki codebase....

**Comment by ablodge** [comment]
What's the view associated with loading a language article? I'm trying to profile the function for calling it using `@silk_profile(name='Language Article').
`

**Comment by nschneid** [comment]
https://github.com/nert-gu/Xposition/blob/1e81ed335147bf99257fe70a7568ad0060138fe1/wiki/plugins/metadata/views.py#L73

**Comment by nschneid** [comment]
Never mind, that's the view for the language form. I think all articles use

https://github.com/nert-gu/Xposition/blob/1e81ed335147bf99257fe70a7568ad0060138fe1/wiki/views/article.py#L33

**Comment by ablodge** [comment]
Is there a function like `get()` that I can profile?

**Comment by nschneid** [comment]
Not sure. What is `get()` supposed to do?

**Comment by ablodge** [comment]
Whichever function is called whenever the article is loaded into a browser, we would like to profile that to see why it takes a long time to load.

**Comment by nschneid** [comment]
Maybe `ArticleView.dispatch()`? It looks like it is decorated by https://github.com/nert-gu/Xposition/blob/1e81ed335147bf99257fe70a7568ad0060138fe1/wiki/decorators.py#L36, where the article path lookup happens.

**Comment by ablodge** [comment]
How to install silk:
```
pip unistall django-mptt
pip install django-mptt==0.8.7
pip unistall django-categories
pip install django-categories==1.5
pip install django-silk
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic
```

**Comment by ablodge** [comment]
I switched from silk (which is still buggy with our code) to [debug-tools](https://django-debug-toolbar.readthedocs.io/) which is installed by default.

**Comment by nschneid** [comment]
Ideas that may help:

- [ ] On language pages, remove the list of usages.
- [ ] Consider not creating a category for every adposition and usage. This may be slowing down the Edit Article page because the full list of categories is loaded in the sidebars. To test this, try truncating the list of categories that are loaded: https://github.com/nert-gu/Xposition/blob/824a231bd0f8076bfaca6ca7dc63ad164a04309d/wiki/plugins/categories/forms.py#L43 and https://github.com/nert-gu/Xposition/blob/824a231bd0f8076bfaca6ca7dc63ad164a04309d/wiki/plugins/categories/forms.py#L82 I suspect this will make the edit page load much faster.

**Comment by nschneid** [comment]
https://docs.djangoproject.com/en/2.0/topics/db/optimization/

In debugging the `html()` methods I noticed that `get_absolute_url()` calls take some time. Perhaps there's an optimization we can do to reduce that.

**Comment by ablodge** [comment]
Okay. 
The loading time is now pretty good. Caching the pages helps a lot. It's not obvious to me that removing the categories sped up the loading, but try it out too.

**Comment by nschneid** [comment]
I did what I could for the `html()` methods on an html-methods branch. The full list of construals is still slow (about 8s for me) but other pages are more reasonable (2–4s). Haven't tried page caching.

**Comment by nschneid** [comment]
Some other things to try:

1. Adding indexes to the database. https://docs.djangoproject.com/en/2.0/topics/db/optimization/#use-standard-db-optimization-techniques By default, each table is indexed by its primary key, but if there are routine lookups on other fields, indexing those can make a massive difference in query time. As there are a lot of joins that involve matching a non-primary key against another table's primary key ("get the adposition whose article is this one", etc.), it may help to index the foreign key and one-to-one fields, including in `Article` and `RevisionPlugin` (which are django-wiki-defined models).

   I suspect indexing a few pivotal fields will make a world of difference.

2. Dotted access across tables (e.g. `lang.article.current_revision.deleted`) involves a series of database queries, which can be expensive. [`select_related()`](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#select-related) may help by loading everything at once. Some form of profiling is probably necessary to find out which of these queries are actually slow.

3. Speed up or reduce use of `deepest_instance`, which performs introspection on objects but is basically shorthand for `metadata.(supersense|adposition|usage)` or `metadatarevision.(supersense|adposition|usage)revision`, due to the way Django model inheritance is implemented.

**Comment by nschneid** [comment]
> it may help to index the foreign key and one-to-one fields, including in `Article` and `RevisionPlugin`

Also probably `MetadataRevision.name` and `Language.slug`.

**Comment by nschneid** [comment]
[Oh:](https://docs.djangoproject.com/en/2.0/ref/models/fields/#foreignkey) "A database index is automatically created on the ForeignKey." So much for that idea.

**Comment by nschneid** [comment]
I've managed to speed up:

- supersense page (tested on Cost) from 2.2s to 1.5s
- construal page (tested on Cost--Cost) from 2.3s to 1.7s
- usage page (tested on en/for/Cost--Cost) from 2.1s to 1.7s
- adposition page (tested on en/for) from 3.3s to 2.7s

by adding the call

```py
.select_related('construal__article__current_revision', 
        'construal__role__article__current_revision', 'construal__function__article__current_revision', 
        'usage__current_revision__metadatarevision__usagerevision__article_revision__article',
        'sentence', 'adposition')
```

when initializing the data tables to avoid hitting the database a bunch of times.

The adposition page is slowest because it lists a bunch of usages.

**Comment by nschneid** [comment]
A `select_related()` call on usage lists speeds up the adposition page from 2.7s to 2.3s. (It doesn't noticeably affect the Cost--Cost supersense page, which only has 2 usages to list.)

Language page (/en): `select_related()` on the adposition list improves from 2.5s to 2.0s.

**Comment by ablodge** [comment]
Are there any Todo items on this issue?

**Comment by nschneid** [comment]
Just #105 I guess
